# Logitech F710 wireless controller
# Deadman (enable) button: Right Trigger
# D<>X button (located on the back panel) must be set to D
teleop:
  takeoff:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: safe_takeoff
    deadman_buttons: [3, 7]  # RT + Y
    axis_mappings: []
  land:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: land
    deadman_buttons: [1, 7]  # RT + A
    axis_mappings: []
  emergency:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: reset
    deadman_buttons: [2, 7] # RT + B
    axis_mappings: []
  sync:
    type: topic
    message_type: "geometry_msgs/Point"
    topic_name: "set_position"
    deadman_buttons: [0, 7]
    message_value:
      - target: x
        value: 0
      - target: y
        value: 0
      - target: z
        value: 0
  follow_on:
    type: topic
    message_type: "drone_arena_msgs/TargetSource"
    topic_name: "target_source"
    message_value:
      - target: mode
        value: 6
      - target: topic
        value: /head/mocap_odom
    deadman_buttons: [0, 6]
  throw:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: "throw_takeoff"
    deadman_buttons: [3, 6]
    axis_mappings: []
  palm:
    type: topic
    message_type: "std_msgs/Empty"
    topic_name: "palm_land"
    deadman_buttons: [1, 6]
    axis_mappings: []
  # flip_0:
  #   type: topic
  #   message_type: "std_msgs/UInt8"
  #   topic_name: "flip"
  #   deadman_buttons: [5, 6]
  #   message_value:
  #     - target: data
  #       value: 0
  # flip_1:
  #   type: topic
  #   message_type: "std_msgs/UInt8"
  #   topic_name: "flip"
  #   deadman_buttons: [4, 6]
  #   message_value:
  #     - target: data
  #       value: 1
